/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#93000d',
        'on-surface': '#191c1e',
        'on-tertiary': '#ffffff',
        'executive-gold': '#F4B400',
        'inverse-primary': '#b5c8e3',
        'inverse-on-surface': '#eff1f4',
        'border-ice': '#E8EDF3',
        'surface-tint': '#4e6077',
        'on-secondary-fixed-variant': '#005047',
        'on-error-container': '#93000a',
        'text-primary': '#172B4D',
        'error-container': '#ffdad6',
        'outline-variant': '#c4c6cd',
        'primary-fixed': '#d1e4ff',
        'primary-fixed-dim': '#b5c8e3',
        'surface-container-highest': '#e0e3e6',
        'surface-container': '#eceef1',
        outline: '#74777d',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3133',
        'on-primary-fixed': '#081d30',
        'surface-bright': '#f7f9fc',
        'surface-container-high': '#e6e8eb',
        'surface-variant': '#e0e3e6',
        secondary: '#006b5f',
        primary: '#00050e',
        surface: '#f7f9fc',
        'on-background': '#191c1e',
        'on-secondary-container': '#006f63',
        'primary-container': '#0b1f33',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#7587a0',
        'surface-container-low': '#f2f4f7',
        'secondary-fixed': '#79f7e3',
        'secondary-fixed-dim': '#59dbc7',
        'text-secondary': '#6B778C',
        'secondary-container': '#76f4e0',
        background: '#f7f9fc',
        'surface-white': '#FFFFFF',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#36485e',
        error: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      /* Do NOT override Tailwind sm/md/lg/xl — use standard p-4, gap-6, etc. */
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        gutter: '16px',
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-bold': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'label-small': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
      boxShadow: {
        card: '0 4px 6px -1px rgba(11, 31, 51, 0.05), 0 2px 4px -2px rgba(11, 31, 51, 0.04)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')({ strategy: 'class' })],
}
